from requests import *


print(get('http://localhost:8080/api/v2/users').json())
print(get('http://localhost:8080/api/v2/users/3').json())
print(get('http://localhost:8080/api/v2/users/999').json())
print(get('http://localhost:8080/api/v2/users/hello_world').json())
print(post('http://localhost:8080/apiv2//users').json())
print(post('http://localhost:8080/api/v2/users', json={'name': 'Abdrew','age': 45}).json())
print(post('http://localhost:8080/api/v2/users', json={'id': 6, 'surname': 'Black', 'name': 'Andre', 'age': 45, 'position': 'capitan', 'speciality': 'engineer', 'address': 'module 1', 'email': 'Andrew1@mars.com', 'password': 'CoolDavid2000'}).json())
print(post('http://localhost:8080/api/v2/users', json={'id': 7, 'surname': 'Black', 'name': 'Andre', 'age': 45, 'position': 'capitan', 'speciality': 'engineer', 'address': 'module 1', 'email': 'Andrew@mars.com', 'password': 'CoolDavid2000'}).json())
print(get('http://localhost:8080/api/v2/users').json())
print(post('http://localhost:8080/api/v2/users', json={'id': 9, 'surname': 'Li', 'name': 'Oliver', 'age': 43, 'position': 'assistant', 'speciality': 'engineer', 'address': 'module 1', 'email': 'oliverLi2@help.com', 'password': 'oliver78'}).json())
print(delete('http://localhost:8080/api/v2/users/999').json())
print(delete('http://localhost:8080/api/v2/users/hello_world').json())
print(delete('http://localhost:8080/api/v2/users/9').json())
print(get('http://localhost:8080/api/v2/users').json())
print(post('http://localhost:8080/api/v2/users', json={ 'id': 10, 'surname': 'Li', 'name': 'Oliver', 'age': 43, 'position': 'assistant', 'speciality': 'engineer', 'address': 'module 1', 'email': 'oliverLi2@help.com', 'password': 'oliver78'}).json())
print(put('http://localhost:8080/api/v2/users/2').json())
print(put('http://localhost:8080/api/v2/users/2', json={'something': 12}).json())
print(put('http://localhost:8080/api/v2/users/999', json={'address': 'module 2'}).json())
print(put('http://localhost:8080/api/v2/users/2', json={'address': 'module 2'}).json())
print(get('http://localhost:8080/api/v2/users').json())